name: Training Gensim's Word2Vec on non-language data
description: Training Gensim's Word2Vec on non-language data
author: Cloudera Inc.
specification_version: 1.0
prototype_version: 1.0
date: "2021-07-13"
api_version: 1

runtimes:
  - editor: Jupyter
    kernel: Python 3.8
    edition: Technical Preview
    version: 2021.11

tasks:
  - type: run_session
    name: Start JupyterLab Session
    script: train_gensim_word2vec.ipynb
    memory: 4
    cpu: 2
