name: Training Gensim's Word2Vec on non-traditional corpora
description: Training Gensim's Word2Vec on non-traditional corpora
author: Cloudera Inc.
specification_version: 1.0
prototype_version: 1.0
date: "2021-07-13"
api_version: 1


# add declarations to run script jobs